add 'kubectl kots gitops-info -n ns' to get gitops providers and keypairs
replicatedhq/kots pull request #1225
Opened 2020-11-06 07:15 UTC by laverya

this is a hidden command

This also moves the 'gitops' package into kots from kotsadm in order to be accessible to the CLI

2020-11-06 16:14 UTC, salahalsaleh commented on pkg/gitops/gitops.go
> +	if kuberneteserrors.IsNotFound(err) {
i think this should fail if the encryption key is not found

2020-11-06 16:16 UTC, salahalsaleh commented
why move `pkg/gitops/clone.go`, `pkg/gitops/key.go` and `pkg/gitops/types/gitops_interface.go`? i think they should stay in kotsadm as the functions/types defined there are all related to kotsadm functionality, not kots.

2020-11-06 16:18 UTC, salahalsaleh commented on cmd/kots/cli/gitops-info.go
> +			keypairs, err := gitops.GetGitopsKeypairs(namespace)
i think this should be an API call instead of moving the kotsadm packages to kots

2020-11-06 16:18 UTC, salahalsaleh requested changes
i think this should be an API call instead of moving the kotsadm packages to kots

2020-11-06 16:18 UTC, salahalsaleh commented on cmd/kots/cli/gitops-info.go
> +			keypairs, err := gitops.GetGitopsKeypairs(namespace)
i think this should be an API call instead of moving the kotsadm packages to kots

2021-03-11 23:47 UTC, AmberAlston commented
@laverya should this PR still be open?

2024-01-11 23:38 UTC, closed without merging