RestoreSnapshotModal - ch29948/restore-modal-requests-app-slug-which-may
replicatedhq/kots pull request #1451
Opened 2021-01-22 23:24 UTC by abhiaiyer91

Added clarifying copy in RestoreSnapshotModal. 

I originally was trying to get to this modal organically using the product, but overall my speed to add this change was pretty slow. I've added storybook to the web project so we can iterate on stateless components faster.

![image](https://user-images.githubusercontent.com/2359375/105559405-eda10e80-5cc5-11eb-90de-c91a0fa7a97c.png)

2021-01-22 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/kots?pullRequest=1451) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/kots?pullRequest=1451) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/kots?pullRequest=1451) it.</sub>

2021-01-26 16:14 UTC, AmberAlston commented
@jgruica or @GraysonNull Can one of you review this PR please? Thanks!

2021-01-26 16:15 UTC, jgruica approved these changes

2021-01-26 18:37 UTC, GraysonNull requested changes

2021-01-26 18:37 UTC, GraysonNull commented on kotsadm/web/src/components/modals/RestoreSnapshotModal.jsx
> +            <p className="u-fontSize--normal u-fontWeight--normal u-color--dustyGray u-lineHeight--normal">We require you enter a matching app slug name as an additional confirmation you wish to proc
I'd like to make a copy change suggestion to better match how we've spoke about this in other similar scenarios like requiring app name to delete an app in vendor web. 

`To confirm that you want to delete this snapshot, please type it's slug in the input as it appears below.`

2021-01-26 18:38 UTC, GraysonNull commented on kotsadm/web/src/components/modals/RestoreSnapshotModal.jsx
> +            <p className="u-fontSize--normal u-fontWeight--normal u-color--dustyGray u-lineHeight--normal">We require you enter a matching app slug name as an additional confirmation you wish to proc
After that change is made i'm good merging this. Thanks for removing Storybook until we can have a larger conversation about it's implementation.

2021-01-26 20:57 UTC, platformfirstco commented
@GraysonNull i've updated the copy!

2021-01-26 20:58 UTC, GraysonNull commented
Great, thank you!. One other question, why is there four "remove storybook" commits? That feels...odd

2021-01-26 21:10 UTC, platformfirstco commented
> Great, thank you!. One other question, why is there four "remove storybook" commits? That feels...odd

Sorry about that! Every commit i thought i removed storybook, there was something lingering. Would you like me to reopen a PR without those commits?

2021-01-26 21:19 UTC, GraysonNull commented
Ah gotcha. No it's ok, maybe just squash before merging. I was just wanting to make sure there wasn't anything messed up with the git history

2021-01-27 02:50 UTC, abhiaiyer91 commented
@GraysonNull can you squash and merge when you get a chance?

2021-01-27 17:27 UTC, merged