non-interactive admin console password reset
replicatedhq/kots pull request #1687
Opened 2021-03-29 23:29 UTC by salahalsaleh

2021-03-29 23:32 UTC, divolgin approved these changes

2021-03-29 23:34 UTC, marccampbell commented on cmd/kots/cli/reset-password.go
> +				log.ActionWithoutSpinner("Reset the admin console password for %s", namespace)
@salahalsaleh I think this sentence should be worded clearer. How about something like "The password for the Admin Console has been reset"...

2021-03-30 01:39 UTC, divolgin approved these changes

2021-03-30 01:44 UTC, emosbaugh requested changes

2021-03-30 01:44 UTC, emosbaugh commented on cmd/kots/cli/reset-password.go
> +					os.Exit(1)
Log?

2021-03-30 02:18 UTC, divolgin approved these changes

2021-03-30 02:24 UTC, closed without merging