don't autodeploy if preflights are failing
replicatedhq/kots pull request #2606
Opened 2022-03-11 22:09 UTC by kcboyle

#### What type of PR is this?
type::bug

#### What this PR does / why we need it:
This PR fixes a bug where auto-deploys would deploy updates to the application automatically even when the preflight checks were failing

#### Does this PR introduce a user-facing change?

```release-note
- fixes a bug with auto deploys where deployments would happen regardless of preflight success or failure. Auto-deploys will now only deploy if the preflights succeed
```

#### Does this PR require documentation?
NONE

2022-03-11 22:16 UTC, kcboyle commented
<img width="1356" alt="Screen Shot 2022-03-11 at 1 57 18 PM" src="https://user-images.githubusercontent.com/1361223/157979933-6df8d045-3326-4de1-b92c-870e913523dc.png">
Screenshot of log message when the preflights fail

2022-03-11 22:22 UTC, DanStough approved these changes

2022-03-11 22:57 UTC, pavansokkenagaraj requested changes

2022-03-11 22:57 UTC, pavansokkenagaraj commented on pkg/updatechecker/updatechecker.go
> +	}
preflight result doesn't account for failed analyzer

preflightresult.results[].isFail=true, the deployments should be blocked.

+ when there is no preflight spec in the app, we may need to test the edge case

2022-03-21 22:10 UTC, kcboyle commented
messed up the rebase on this one. opening up a [new PR](https://github.com/replicatedhq/kots/pull/2628) that is fixed

2022-03-21 22:10 UTC, closed without merging

2022-03-22 16:58 UTC, sgalsaleh commented on pkg/updatechecker/updatechecker.go
> +	if preflightResult == nil || len(preflightResult.Result) == 0 {
this should not fail, some apps don't have preflights