bug: setting https proxy to the right value
replicatedhq/kots pull request #3905
Opened 2023-05-24 13:29 UTC by ricardomaraschini

#### What this PR does / why we need it:

In order to handle two distinct proxies that may exist in the system separately, it is necessary to treat them individually. The presence of a second environment variable, `PROXY_HTTPS_ADDRESS`, indicates the configured https proxy.

This PR ensures the appropriate utilization of the correct env variable for the https proxy.

#### Which issue(s) this PR fixes:
Fixes # [sc-70304]

#### Does this PR introduce a user-facing change?
```release-note
Kots starts to support different proxies for HTTP and HTTPS access.
```

2023-05-24 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/kots?pullRequest=3905) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/kots?pullRequest=3905) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/kots?pullRequest=3905) it.</sub>

2023-06-01 09:52 UTC, camilamacedo86 approved these changes
It shows OK for me 👍

2023-06-01 13:32 UTC, emosbaugh requested changes
in order to make this backwards compatible could you set PROXY_HTTPS_ADDRESS = PROXY_HTTP_ADDRESS when unset?

2023-06-01 14:25 UTC, ricardomaraschini commented
> in order to make this backwards compatible could you set PROXY_HTTPS_ADDRESS = PROXY_HTTP_ADDRESS when unset?

That makes total sense. Done.

2023-06-01 15:23 UTC, emosbaugh approved these changes

2023-06-01 16:13 UTC, merged