feat: allow migrate from HelmChart v1beta1 to v1beta2 if Helm --take-ownership is set
replicatedhq/kots pull request #5046
Opened 2024-12-12 22:47 UTC by nvanthao

#### What this PR does / why we need it:

We currently don't allow migration from existing Helm installation of `v1beta1` with `useHelmInstall: false` to Helm `v1beta2`.

As Helm CLI will soon support `--take-ownership` flag, this will be possible.

This PR allows the application pull for Helm chart with same name in `v1beta2`, as long as there is `--take-ownership` flag in Helm additional upgrade flags.

Demo: https://www.loom.com/share/db17e620509843d884fbcf98605daaed?t=281

#### Which issue(s) this PR fixes:

Story: https://app.shortcut.com/replicated/story/117029/add-keep-annotation-to-kots

#### Does this PR require a test?

NONE

#### Does this PR require a release note?

```release-note
NONE
```

#### Does this PR require documentation?

Current docs will have to be updated after the change is merged and upstream Helm CLI supports `--take-ownership` flag

- https://docs.replicated.com/vendor/helm-v2-migrate#usehelminstall-false-limitation
- https://docs.replicated.com/reference/custom-resource-helmchart#usehelminstall

2024-12-12 23:05 UTC, xavpaice commented
This needs to be merged alongside updating Helm to either use the version with `--take-ownership` merged and released, or our fork of it that does.

2024-12-13 00:18 UTC, nvanthao commented
I've updated the PR with fetching from Helm PR that supports `--take-ownership` and build it.

2024-12-19 15:07 UTC, sgalsaleh commented on deploy/melange.yaml.tmpl
> +      git clone --depth 1 https://github.com/helm/helm.git
should use melange `git-checkout` like this: https://github.com/wolfi-dev/os/blob/9a2344577f49c44a869a12f186cb6a11318fe4fd/checksec.yaml#L25-L34

2024-12-19 15:08 UTC, sgalsaleh commented on deploy/melange.yaml.tmpl
> +      git clone --depth 1 https://github.com/helm/helm.git
and use a specific commit

2024-12-19 15:12 UTC, sgalsaleh commented on deploy/melange.yaml.tmpl
> -      ln -s /usr/bin/helm ${DESTDIR}/usr/local/bin/helm
you'll also need to remove the helm binary from the apko file: https://github.com/replicatedhq/kots/blob/main/deploy/apko.yaml.tmpl#L16

2024-12-19 15:13 UTC, sgalsaleh commented on deploy/melange.yaml.tmpl
> +      mv bin/helm "${DESTDIR}/usr/local/bin/"
you need to run `mkdir -p ${DESTDIR}/usr/local/bin/` first. which is why CI is failing

2024-12-20 05:26 UTC, nvanthao commented
Many thanks @sgalsaleh! I have made the requested changes accordingly and notice the Melange and Apko actions completed successfully. Please let me know how it goes.

2024-12-20 15:41 UTC, sgalsaleh approved these changes

2024-12-22 22:21 UTC, xavpaice commented
Now that the change is merged in Helm, we can use the 'main' branch rather than the PR branch

2024-12-22 22:48 UTC, nvanthao commented
Helm `main` branch is for their `v4` and the "main" for current change is `dev-v3`

2024-12-22 22:49 UTC, nvanthao commented
apologies @sgalsaleh could you help me approve the change again? I removed the `expected-commit` because we are cloning Helm with depth 1 and the commit is gone with newer commits from Helm.

2025-01-16 17:14 UTC, scottrigby commented
Update: The new `--take-ownership` flag for install and upgrade commands has landed in Helm! Released yesterday [Helm v3.17.0](https://github.com/helm/helm/releases/tag/v3.17.0). Congrats to everyone who worked on this 👏🎉

2025-01-17 15:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/kots?pullRequest=5046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/kots?pullRequest=5046) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nvanthao<br/>:x: adamancini<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/kots?pullRequest=5046) it.</sub>

2025-01-17 19:52 UTC, xavpaice requested changes
needs update now that Helm got released.

2025-01-17 19:52 UTC, xavpaice commented on deploy/melange.yaml.tmpl
> +      branch: dev-v3
We don't need this any more :)

2025-01-19 14:22 UTC, nvanthao commented
Hi @sgalsaleh @laverya,

I have removed the Helm PR setup due to `--take-ownership` flag is now in release `v3.17.0`.

Could you help me with the final approval?

Cheers,

2025-01-20 01:59 UTC, xavpaice approved these changes
Thanks for the update.  Needs KOTS team to review.

2025-01-21 14:42 UTC, sgalsaleh commented
Product question: should we add the flag automatically for a more seamless migration?

2025-01-21 17:19 UTC, adamancini commented
@xavpaice signed CLA

2025-01-21 21:42 UTC, ajp-io commented
> Product question: should we add the flag automatically for a more seamless migration?

How would we detect this? And can we deterministically detect it, or could the vendor intend something else. I always like making things easier, but if this migration is being heavily moderated by Replicated (like we're helping vendors make these changes and whatnot), then the steps are pretty clear and the risk of doing it automatically might not be necessary.

So I could go either way depending on whether we think that's really necessary.

2025-01-22 15:43 UTC, merged